<?php

/**
 * This file is part of the Spryker Commerce OS.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

namespace PyzTest\Zed\AntelopeType\Business;

use Codeception\Test\Unit;
use PyzTest\Zed\AntelopeType\AntelopeTypeBusinessTester;

/**
 * Auto-generated group annotations
 *
 * @group PyzTest
 * @group Zed
 * @group AntelopeType
 * @group Business
 * @group Facade
 * @group AntelopeTypeFacadeTest
 * Add your own group annotations below this line
 */
class AntelopeTypeFacadeTest extends Unit
{
    /**
     * @var \PyzTest\Zed\AntelopeType\AntelopeTypeBusinessTester
     */
    protected AntelopeTypeBusinessTester $tester;

    /**
     * @return void
     */
    public function testGetAntelopeTypeCollection(): void
    {
        // This is an autogenerated test, please complete me.
        $this->assertTrue(false);
    }

    /**
     * @return void
     */
    public function testCreateAntelopeType(): void
    {
        // This is an autogenerated test, please complete me.
        $this->assertTrue(false);
    }
}
